name: 预览

on: pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false
        
      - run: >
          echo 环境准备完成~ "$(pnpm -v)"
          echo pnpm: "$(pnpm -v)"
          echo node: "$(node -v)"
          echo npm:  "$(npm -v)"

      - name: Install
        run: pnpm i


      - name: Generate
        run: pnpm generate

      - name: Publish
        run: pnpm -r publish --report-summary
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - run: echo 运行完成~    
      



